# Generated by Django 3.0.2 on 2020-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='contains_peanuts',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='spicy',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.ManyToManyField(help_text="The menus that this category belongs to, i.e. 'Lunch'.", related_name='_menu_menu_+', to='menu.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='additional_text',
            field=models.CharField(blank=True, help_text="The additional text is any bit of related information to go along with a menu category, i.e. the 'Pasta' category might have details that say 'All entrees come with salad and bread'.", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=32, verbose_name='menu category name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0, help_text='The order is the order that this category should appear in when rendered on the templates.'),
        ),
        migrations.DeleteModel(
            name='MenuCat',
        ),
    ]
