# Generated by Django 3.0.2 on 2020-01-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200104_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item on the menu.', max_length=48)),
                ('description', models.CharField(blank=True, help_text='The description is a simple text description of the menu item.', max_length=128, null=True)),
                ('order', models.IntegerField(default=0, help_text='The order is to specify the order in which items show up on the menu.', verbose_name='order')),
                ('menu', models.ManyToManyField(help_text="The menus that this category belongs to, i.e. 'Lunch'.", related_name='_menucategory_menu_+', to='menu.Menu')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
