# Generated by Django 3.0.2 on 2020-01-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='menu',
            field=models.ManyToManyField(help_text="The menus that this category belongs to, i.e. 'Lunch'.", related_name='menucategory', to='menu.Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_category',
            field=models.ManyToManyField(help_text="The menus that this category belongs to, i.e. 'Lunch'.", related_name='menuitem', to='menu.MenuCategory'),
        ),
    ]
